Target = "OBC"
PacketID = "0x90"
"Enable/Disable" = "ENABLE"
IsRestricted = "FALSE"
"Local Var" = ""

[[tlm]]
type = "uint16_t"
[[tlm.comp]]
name = "PH.VER"
bitlen = 3
[[tlm.comp]]
name = "PH.TYPE"
bitlen = 1
[[tlm.comp]]
name = "PH.SH_FLAG"
bitlen = 1
[[tlm.comp]]
name = "PH.APID"
bitlen = 11


[[tlm]]
type = "uint16_t"
[[tlm.comp]]
name = "PH.SEQ_FLAG"
bitlen = 2
[[tlm.comp]]
name = "PH.SEQ_COUNT"
bitlen = 14


[[tlm]]
type = "uint16_t"
name = "PH.PACKET_LEN"

[[tlm]]
type = "uint8_t"
name = "SH.VER"

[[tlm]]
type = "uint32_t"
name = "SH.TI"

[[tlm]]
type = "uint8_t"
name = "SH.TLM_ID"
is_hex = true

[[tlm]]
type = "double"
name = "SH.GLOBAL_TIME"

[[tlm]]
type = "uint32_t"
name = "SH.ON_BOARD_SUBNET_TIME"

[[tlm]]
type = "uint8_t"
name = "SH.DEST_FLAGS"
is_hex = true

[[tlm]]
type = "uint8_t"
name = "SH.DR_PARTITION"
