[[bct]]
comment = """Block Cmds for Mode Transition (シーケンスリスト)
./src_user/Settings/Modes/Transitions/ で定義"""

[[bct]]
name = "BC_SL_START_UP_TO_INITIAL"
bcid = 0
is_danger = true

[[bct]]
name = "BC_SL_NOP "
bcid = 17
is_danger = true

[[bct]]
comment = """Block Cmds for TaskList (タスクリスト) : 286-300
./src_user/Settings/Modes/TaskLists/ で定義"""

[[bct]]
name = "BC_TL_START_UP"
bcid = 20
is_danger = true

[[bct]]
name = "BC_TL_INITIAL"
bcid = 21
is_danger = true

[[bct]]
comment = """Block Cmds for Elements (App Rotator, Combinar)
./src_user/Settings/Modes/TaskLists/Elements/ で定義"""

[[bct]]
name = "BC_AR_DEBUG_DISPLAY_INI"
bcid = 40
is_danger = true

[[bct]]
name = "BC_AR_DRIVERS_UPDATE_INI"
bcid = 42
is_danger = true

[[bct]]
name = "BC_AR_GS_RELATED_PROCESS"
bcid = 44
is_danger = true

[[bct]]
name = "BC_AC_TLM_CMD_HIRATE"
bcid = 50
is_danger = true

[[bct]]
comment = """==== 各系領域 ====
./C2A/TlmCmd/NormalBlockCommandDefinition/で定義
アノマリハンドラはBC_AH_など，接頭辞を適切につけること！"""

[[bct]]
comment = "CDH:60-79"

[[bct]]
name = "BC_HK_CYCLIC_TLM"
bcid = 60
sname = "BC_HK10S"
is_deploy = true
is_setblockposition = true
is_clear = true
is_activate = true
is_inactivate = true

[[bct]]
name = "BC_RESERVED_FOR_HK"
bcid = 77
desc = "EM電気試験でのコマンドファイルとのバッティングを防ぐ"

[[bct]]
comment = """COMM:90-99
==== 地上からupする“のみ”領域 ====
C2Aでは使用しない
==== 追加領域 ====
Telemetry Manager"""

[[bct]]
q_range = [0, 9]
block_num = 1
[[bct.block]]
name = "BC_TLM_MGR??"
bcid = "35??"

[[bct]]
comment = "Test"

[[bct]]
name = "BC_TEST_EH_RESPOND"
bcid = 360

[[bct]]
name = "BC_TEST_BCL"
bcid = 361

