/**
 * @file
 * @brief  コマンド定義
 * @note   このコードは自動生成されています！
 */
# ifndef COMMAND_DEFINITIONS_H_
# define COMMAND_DEFINITIONS_H_

typedef enum
{
  AOBC_Cmd_CODE_NOP = 0x0,
  AOBC_Cmd_CODE_TMGR_SET_TIME = 0x1,
  AOBC_Cmd_CODE_TMGR_UPDATE_UNIXTIME = 0x2,
  AOBC_Cmd_CODE_TMGR_SET_UTL_UNIXTIME_EPOCH = 0x3,
  AOBC_Cmd_CODE_TMGR_SET_CYCLE_CORRECTION = 0x4,
  AOBC_Cmd_CODE_TMGR_RESET_CYCLE_CORRECTION = 0x5,
  AOBC_Cmd_CODE_TMGR_CLEAR_UNIXTIME_INFO = 0x6,
  AOBC_Cmd_CODE_AM_REGISTER_APP = 0x7,
  AOBC_Cmd_CODE_AM_INITIALIZE_APP = 0x8,
  AOBC_Cmd_CODE_AM_EXECUTE_APP = 0x9,
  AOBC_Cmd_CODE_AM_SET_PAGE_FOR_TLM = 0xa,
  AOBC_Cmd_CODE_AM_CLEAR_APP_INFO = 0xb,
  AOBC_Cmd_CODE_MM_SET_MODE_LIST = 0xc,
  AOBC_Cmd_CODE_MM_SET_TRANSITION_TABLE = 0xd,
  AOBC_Cmd_CODE_MM_START_TRANSITION = 0xe,
  AOBC_Cmd_CODE_MM_FINISH_TRANSITION = 0xf,
  AOBC_Cmd_CODE_MM_UPDATE_TRANSITION_TABLE_FOR_TLM = 0x10,
  AOBC_Cmd_CODE_TDSP_SET_TASK_LIST = 0x11,
  AOBC_Cmd_CODE_TLCD_CLEAR_ALL_TIMELINE = 0x12,
  AOBC_Cmd_CODE_TLCD_CLEAR_TIMELINE_AT = 0x13,
  AOBC_Cmd_CODE_TLCD_SET_LINE_NO_FOR_TIMELINE_TLM = 0x14,
  AOBC_Cmd_CODE_TLCD_DEPLOY_BLOCK = 0x15,
  AOBC_Cmd_CODE_TLCD_SET_SOE_FLAG = 0x16,
  AOBC_Cmd_CODE_TLCD_SET_LOUT_FLAG = 0x17,
  AOBC_Cmd_CODE_TLCD_SET_PAGE_FOR_TLM = 0x18,
  AOBC_Cmd_CODE_TLCD_CLEAR_ERR_LOG = 0x19,
  AOBC_Cmd_CODE_GENERATE_TLM = 0x1a,

  CMD_CODE_MAX
} CMD_CODE;

# endif
