obc = "MOBC"
Target = "OBC"
PacketID = "0xf8"
"Enable/Disable" = "ENABLE"
IsRestricted = "FALSE"
"Local Var" = ""

[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.VER"
bitlen = 3
[[tlm_field.comp]]
name = "PH.TYPE"
bitlen = 1
[[tlm_field.comp]]
name = "PH.SH_FLAG"
bitlen = 1
[[tlm_field.comp]]
name = "PH.APID"
bitlen = 11


[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.SEQ_FLAG"
bitlen = 2
[[tlm_field.comp]]
name = "PH.SEQ_COUNT"
bitlen = 14


[[tlm_field]]
name = "PH.PACKET_LEN"
type = "uint16_t"

[[tlm_field]]
name = "SH.VER"
type = "uint8_t"

[[tlm_field]]
name = "SH.TI"
type = "uint32_t"

[[tlm_field]]
name = "SH.TLM_ID"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.GLOBAL_TIME"
type = "double"

[[tlm_field]]
name = "SH.ON_BOARD_SUBNET_TIME"
type = "uint32_t"

[[tlm_field]]
name = "SH.DEST_FLAGS"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.DR_PARTITION"
type = "uint8_t"

[[tlm_field]]
name = "DRIVER.REC_STATUS.RET_FROM_IF_RX"
type = "uint8_t"
exp = "(uint8_t)(uart_test_instance->driver.super.config.rec_status_.ret_from_if_rx)"

[[tlm_field]]
name = "DRIVER.RX_COUNT"
type = "uint32_t"
exp = "uart_test_instance->driver.super.config.rx_count_"

[[tlm_field]]
name = "DRIVER0.REC_STATUS.STATUS_CODE"
type = "uint8_t"
exp = "(uint8_t)(uart_test_instance->driver.super.stream_config[0].rec_status_.status_code)"
status = "11.1"

[[tlm_field]]
name = "DRIVER0.REC_STATUS.FIXED_FRAME_LEN"
type = "uint16_t"
exp = "uart_test_instance->driver.super.stream_config[0].rec_status_.fixed_frame_len"

[[tlm_field]]
name = "DRIVER0.RX_FRAME_FIX_COUNT"
type = "uint32_t"
exp = "uart_test_instance->driver.super.stream_config[0].rx_frame_fix_count_"

[[tlm_field]]
name = "DRIVER0.RX_FRAME_REC_LEN"
type = "uint16_t"
exp = "uart_test_instance->driver.super.stream_config[0].rx_frame_rec_len_"

[[tlm_field]]
name = "DRIVER0.IS_RX_BUFFER_CARRY_OVER"
type = "uint8_t"
exp = "uart_test_instance->driver.super.stream_config[0].is_rx_buffer_carry_over_"

[[tlm_field]]
name = "DRIVER1.REC_STATUS.STATUS_CODE"
type = "uint8_t"
exp = "(uint8_t)(uart_test_instance->driver.super.stream_config[1].rec_status_.status_code)"
status = "11.1"

[[tlm_field]]
name = "DRIVER1.REC_STATUS.FIXED_FRAME_LEN"
type = "uint16_t"
exp = "uart_test_instance->driver.super.stream_config[1].rec_status_.fixed_frame_len"

[[tlm_field]]
name = "DRIVER1.RX_FRAME_FIX_COUNT"
type = "uint32_t"
exp = "uart_test_instance->driver.super.stream_config[1].rx_frame_fix_count_"

[[tlm_field]]
name = "DRIVER1.RX_FRAME_REC_LEN"
type = "uint16_t"
exp = "uart_test_instance->driver.super.stream_config[1].rx_frame_rec_len_"

[[tlm_field]]
name = "DRIVER1.IS_RX_BUFFER_CARRY_OVER"
type = "uint8_t"
exp = "uart_test_instance->driver.super.stream_config[1].is_rx_buffer_carry_over_"

