obc = "MOBC"
Target = "OBC"
PacketID = "0x00"
"Enable/Disable" = "ENABLE"
IsRestricted = "FALSE"
"Local Var" = ""

[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.VER"
bitlen = 3
[[tlm_field.comp]]
name = "PH.TYPE"
bitlen = 1
[[tlm_field.comp]]
name = "PH.SH_FLAG"
bitlen = 1
[[tlm_field.comp]]
name = "PH.APID"
bitlen = 11


[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.SEQ_FLAG"
bitlen = 2
[[tlm_field.comp]]
name = "PH.SEQ_COUNT"
bitlen = 14


[[tlm_field]]
name = "PH.PACKET_LEN"
type = "uint16_t"

[[tlm_field]]
name = "SH.VER"
type = "uint8_t"

[[tlm_field]]
name = "SH.TI"
type = "uint32_t"

[[tlm_field]]
name = "SH.TLM_ID"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.GLOBAL_TIME"
type = "double"

[[tlm_field]]
name = "SH.ON_BOARD_SUBNET_TIME"
type = "uint32_t"

[[tlm_field]]
name = "SH.DEST_FLAGS"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.DR_PARTITION"
type = "uint8_t"

[[tlm_field]]
name = "TM_MODE_TIME"
type = "uint32_t"
exp = "(uint32_t)(TMGR_get_master_clock().mode_cycle)"
desc = "モード遷移後経過時刻"

[[tlm_field]]
name = "TM_UTL_UNIXTIME_EPOCH"
type = "double"
exp = "TMGR_get_utl_unixtime_epoch()"
desc = "UTL_cmdで用いるunixtimeの紀元"

[[tlm_field]]
name = "TM_CYCLES_PER_SEC_FIX_RATIO"
type = "double"
exp = "(double)(time_manager->unixtime_info_.cycle_correction)"
desc = "CYCLES_PER_SECの補正倍率. 初期値は1.0"

[[tlm_field]]
name = "MM_STS"
type = "uint8_t"
exp = "(uint8_t)(mode_manager->stat)"
desc = "モード遷移実行状態"

[[tlm_field]]
name = "MM_OPSMODE"
type = "uint8_t"
exp = "(uint8_t)(mode_manager->current_id)"
desc = "現状モード番号"

[[tlm_field]]
name = "MM_OPSMODE_PREV"
type = "uint8_t"
exp = "(uint8_t)(mode_manager->previous_id)"
desc = "直前モード番号"

[[tlm_field]]
name = "TDSP_CURRENT_ID"
type = "uint8_t"
exp = "(uint8_t)(TDSP_info->task_list_id)"
desc = "現状 TaskList ID"

[[tlm_field]]
name = "TDSP_CMD_LAST_ERR_TIME_MASTER"
type = "uint32_t"
exp = "(uint32_t)(TDSP_info->tskd.prev_err.time.total_cycle)"
desc = "最新内部コマンド実行時刻"

[[tlm_field]]
name = "TDSP_CMD_LAST_ERR_TIME_STEP"
type = "uint8_t"
exp = "(uint8_t)(TDSP_info->tskd.prev_err.time.step)"

[[tlm_field]]
name = "TDSP_CMD_LAST_ERR_ID"
type = "uint16_t"
exp = "(uint16_t)(TDSP_info->tskd.prev_err.code)"
desc = "最新内部コマンドID"

[[tlm_field]]
name = "TDSP_CMD_LAST_ERR_STS"
type = "int32_t"
exp = "(int32_t)(TDSP_info->tskd.prev_err.sts)"
status = "7.1"
desc = "最新内部コマンド実行結果"

[[tlm_field]]
name = "GS_RET_FROM_IF_RX"
type = "int32_t"
exp = "(int32_t)gs_driver->latest_info->rx.ret_from_if_rx"

[[tlm_field]]
name = "TCTF_LAST_RECV_ACK"
type = "uint8_t"
exp = "(uint8_t)gs_driver->latest_info->rx.rec_status"
status = "2.10"
desc = "TC Transer Frame DS処理結果"

[[tlm_field]]
name = "TCTF_LAST_RECV_TIME"
type = "uint32_t"
exp = "(uint32_t)gs_driver->latest_info->rx.last_rec_time"
desc = "最新TC Transer Frame受信時刻"

[[tlm_field]]
name = "TCTF_FARM_PW"
type = "uint8_t"
exp = "(uint8_t)gs_validate_info->positive_window_width"
desc = "FARM-1 Positive Window Width"

[[tlm_field]]
name = "TCP_LAST_RECV_ACK"
type = "uint8_t"
exp = "(uint8_t)gs_driver->latest_info->rx.cmd_ack"
status = "13.1"
desc = "最新TCPacket受信処理結果"

[[tlm_field]]
name = "TLM_TX_PORT_TYPE"
type = "uint8_t"
exp = "(uint8_t)gs_driver->tlm_tx_port_type"
status = "2.11"
desc = "TLM の送信情報がUARTのものかGSのものか"

[[tlm_field]]
name = "GS_CMD_COUNTER"
type = "uint32_t"
exp = "PL_count_executed_nodes(&PH_gs_cmd_list)"
desc = "地上局コマンドカウンタ"

[[tlm_field]]
name = "GS_CMD_LAST_EXEC_TIME"
type = "uint32_t"
exp = "(uint32_t)(gs_command_dispatcher->prev.time.total_cycle)"
desc = "最新地上局コマンド実行時刻"

[[tlm_field]]
name = "GS_CMD_LAST_EXEC_ID"
type = "uint16_t"
exp = "(uint16_t)(gs_command_dispatcher->prev.code)"
desc = "最新地上局コマンドID"

[[tlm_field]]
name = "GS_CMD_LAST_EXEC_STS"
type = "int32_t"
exp = "(int32_t)(gs_command_dispatcher->prev.sts)"
status = "7.1"
desc = "最新地上局コマンド実行結果"

[[tlm_field]]
name = "GS_CMD_LAST_ERR_TIME"
type = "uint32_t"
exp = "(uint32_t)(gs_command_dispatcher->prev_err.time.total_cycle)"
desc = "最新地上局コマンド実行時刻"

[[tlm_field]]
name = "GS_CMD_LAST_ERR_ID"
type = "uint16_t"
exp = "(uint16_t)(gs_command_dispatcher->prev_err.code)"
desc = "最新地上局コマンドID"

[[tlm_field]]
name = "GS_CMD_LAST_ERR_STS"
type = "int32_t"
exp = "(int32_t)(gs_command_dispatcher->prev_err.sts)"
status = "7.1"
desc = "最新地上局コマンド実行結果"

[[tlm_field]]
name = "GS_CMD_ERR_COUNTER"
type = "uint32_t"
exp = "(uint32_t)(gs_command_dispatcher->error_counter)"
desc = "地上局コマンド実行異常カウンタ"

[[tlm_field]]
name = "RT_CMD_COUNTER"
type = "uint32_t"
exp = "PL_count_executed_nodes(&PH_rt_cmd_list)"
desc = "内部コマンドカウンタ"

[[tlm_field]]
name = "RT_CMD_LAST_EXEC_TIME"
type = "uint32_t"
exp = "(uint32_t)(realtime_command_dispatcher->prev.time.total_cycle)"
desc = "最新内部コマンド実行時刻"

[[tlm_field]]
name = "RT_CMD_LAST_EXEC_ID"
type = "uint16_t"
exp = "(uint16_t)(realtime_command_dispatcher->prev.code)"
desc = "最新内部コマンドID"

[[tlm_field]]
name = "RT_CMD_LAST_EXEC_STS"
type = "int32_t"
exp = "(int32_t)(realtime_command_dispatcher->prev.sts)"
status = "7.1"
desc = "最新内部コマンド実行結果"

[[tlm_field]]
name = "RT_CMD_LAST_ERR_TIME"
type = "uint32_t"
exp = "(uint32_t)(realtime_command_dispatcher->prev_err.time.total_cycle)"
desc = "最新内部コマンド実行時刻"

[[tlm_field]]
name = "RT_CMD_LAST_ERR_ID"
type = "uint16_t"
exp = "(uint16_t)(realtime_command_dispatcher->prev_err.code)"
desc = "最新内部コマンドID"

[[tlm_field]]
name = "RT_CMD_LAST_ERR_STS"
type = "int32_t"
exp = "(int32_t)(realtime_command_dispatcher->prev_err.sts)"
status = "7.1"
desc = "最新内部コマンド実行結果"

[[tlm_field]]
name = "RT_CMD_ERR_COUNTER"
type = "uint32_t"
exp = "(uint32_t)(realtime_command_dispatcher->error_counter)"
desc = "地上局コマンド実行異常カウンタ"

[[tlm_field]]
name = "TLC_GS.COUNTER"
type = "uint32_t"
exp = "PL_count_executed_nodes(&PH_tl_cmd_list[TLCD_ID_FROM_GS])"
desc = "TL0コマンドカウンタ"

[[tlm_field]]
name = "TLC_GS.QUEUED"
type = "uint8_t"
exp = "(uint8_t)(PL_count_active_nodes(&PH_tl_cmd_list[TLCD_ID_FROM_GS]))"
desc = "TL0登録コマンド数"

[[tlm_field]]
name = "TLC_GS.LAST_EXEC_TIME"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS].prev.time.total_cycle)"
desc = "最新TL0コマンド実行時刻"

[[tlm_field]]
name = "TLC_GS.LAST_EXEC_ID"
type = "uint16_t"
exp = "(uint16_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS].prev.code)"
desc = "最新TL0コマンドID"

[[tlm_field]]
name = "TLC_GS.LAST_EXEC_STS"
type = "int32_t"
exp = "(int32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS].prev.sts)"
status = "7.1"
desc = "最新TL0コマンド実行結果"

[[tlm_field]]
name = "TLC_GS.LAST_ERR_TIME"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS].prev_err.time.total_cycle)"
desc = "最新TL0コマンド実行時刻"

[[tlm_field]]
name = "TLC_GS.LAST_ERR_ID"
type = "uint16_t"
exp = "(uint16_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS].prev_err.code)"
desc = "最新TL0コマンドID"

[[tlm_field]]
name = "TLC_GS.LAST_ERR_STS"
type = "int32_t"
exp = "(int32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS].prev_err.sts)"
status = "7.1"
desc = "最新TL0コマンド実行結果"

[[tlm_field]]
name = "TLC_GS.ERR_COUNTER"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS].error_counter)"
desc = "地上局コマンド実行異常カウンタ"

[[tlm_field]]
name = "TLC_GS.SOE_FLAG"
type = "uint8_t"
exp = "(uint8_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS].stop_on_error)"
status = "2.12"

[[tlm_field]]
name = "TLC_GS.LOCKOUT_FLAG"
type = "uint8_t"
exp = "(uint8_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS].lockout)"
status = "2.13"

[[tlm_field]]
name = "TLC_GS.NEXT_TIME"
type = "uint32_t"
exp = "(PL_is_empty(&(PH_tl_cmd_list[TLCD_ID_FROM_GS])) ? 0 : (uint32_t)CCP_get_ti((const CommonCmdPacket*)(PL_get_head(&(PH_tl_cmd_list[TLCD_ID_FROM_GS]))->packet)))"
desc = "次TL0コマンド実行時刻"
note = "変数指定が大変なことに…"

[[tlm_field]]
name = "TLC_GS.NEXT_ID"
type = "uint16_t"
exp = "(uint16_t)(PL_is_empty(&(PH_tl_cmd_list[TLCD_ID_FROM_GS])) ? 0 : CCP_get_id((const CommonCmdPacket*)(PL_get_head(&(PH_tl_cmd_list[TLCD_ID_FROM_GS]))->packet)))"
desc = "次TL0コマンドID"
note = "変数指定が大変なことに…"

[[tlm_field]]
name = "TLC_BC.COUNTER"
type = "uint32_t"
exp = "PL_count_executed_nodes(&PH_tl_cmd_list[TLCD_ID_DEPLOY_BC])"
desc = "TL1コマンドカウンタ"

[[tlm_field]]
name = "TLC_BC.QUEUED"
type = "uint8_t"
exp = "(uint8_t)(PL_count_active_nodes(&PH_tl_cmd_list[TLCD_ID_DEPLOY_BC]))"
desc = "TL1登録コマンド数"

[[tlm_field]]
name = "TLC_BC.LAST_EXEC_TIME"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_BC].prev.time.total_cycle)"
desc = "最新TL1コマンド実行時刻"

[[tlm_field]]
name = "TLC_BC.LAST_EXEC_ID"
type = "uint16_t"
exp = "(uint16_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_BC].prev.code)"
desc = "最新TL1コマンドID"

[[tlm_field]]
name = "TLC_BC.LAST_EXEC_STS"
type = "int32_t"
exp = "(int32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_BC].prev.sts)"
status = "7.1"
desc = "最新TL1コマンド実行結果"

[[tlm_field]]
name = "TLC_BC.LAST_ERR_TIME"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_BC].prev_err.time.total_cycle)"
desc = "最新TL1コマンド実行時刻"

[[tlm_field]]
name = "TLC_BC.LAST_ERR_ID"
type = "uint16_t"
exp = "(uint16_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_BC].prev_err.code)"
desc = "最新TL1コマンドID"

[[tlm_field]]
name = "TLC_BC.LAST_ERR_STS"
type = "int32_t"
exp = "(int32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_BC].prev_err.sts)"
status = "7.1"
desc = "最新TL1コマンド実行結果"

[[tlm_field]]
name = "TLC_BC.ERR_COUNTER"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_BC].error_counter)"
desc = "地上局コマンド実行異常カウンタ"

[[tlm_field]]
name = "TLC_BC.SOE_FLAG"
type = "uint8_t"
exp = "(uint8_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_BC].stop_on_error)"
status = "2.12"

[[tlm_field]]
name = "TLC_BC.LOCKOUT_FLAG"
type = "uint8_t"
exp = "(uint8_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_BC].lockout)"
status = "2.13"

[[tlm_field]]
name = "TLC_BC.NEXT_TIME"
type = "uint32_t"
exp = "(PL_is_empty(&(PH_tl_cmd_list[TLCD_ID_DEPLOY_BC])) ? 0 : (uint32_t)CCP_get_ti((const CommonCmdPacket*)(PL_get_head(&(PH_tl_cmd_list[TLCD_ID_DEPLOY_BC]))->packet)))"
desc = "次TL1コマンド実行時刻"
note = "変数指定が大変なことに…"

[[tlm_field]]
name = "TLC_BC.NEXT_ID"
type = "uint16_t"
exp = "(uint16_t)(PL_is_empty(&(PH_tl_cmd_list[TLCD_ID_DEPLOY_BC])) ? 0 : CCP_get_id((const CommonCmdPacket*)(PL_get_head(&(PH_tl_cmd_list[TLCD_ID_DEPLOY_BC]))->packet)))"
desc = "次TL1コマンドID"
note = "変数指定が大変なことに…"

[[tlm_field]]
name = "TLC_TLM.COUNTER"
type = "uint32_t"
exp = "PL_count_executed_nodes(&PH_tl_cmd_list[TLCD_ID_DEPLOY_TLM])"
desc = "TL1コマンドカウンタ"

[[tlm_field]]
name = "TLC_TLM.QUEUED"
type = "uint8_t"
exp = "(uint8_t)(PL_count_active_nodes(&PH_tl_cmd_list[TLCD_ID_DEPLOY_TLM]))"
desc = "TL1登録コマンド数"

[[tlm_field]]
name = "TLC_TLM.LAST_EXEC_TIME"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_TLM].prev.time.total_cycle)"
desc = "最新TL1コマンド実行時刻"

[[tlm_field]]
name = "TLC_TLM.LAST_EXEC_ID"
type = "uint16_t"
exp = "(uint16_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_TLM].prev.code)"
desc = "最新TL1コマンドID"

[[tlm_field]]
name = "TLC_TLM.LAST_EXEC_STS"
type = "int32_t"
exp = "(int32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_TLM].prev.sts)"
status = "7.1"
desc = "最新TL1コマンド実行結果"

[[tlm_field]]
name = "TLC_TLM.LAST_ERR_TIME"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_TLM].prev_err.time.total_cycle)"
desc = "最新TL1コマンド実行時刻"

[[tlm_field]]
name = "TLC_TLM.LAST_ERR_ID"
type = "uint16_t"
exp = "(uint16_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_TLM].prev_err.code)"
desc = "最新TL1コマンドID"

[[tlm_field]]
name = "TLC_TLM.LAST_ERR_STS"
type = "int32_t"
exp = "(int32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_TLM].prev_err.sts)"
status = "7.1"
desc = "最新TL1コマンド実行結果"

[[tlm_field]]
name = "TLC_TLM.ERR_COUNTER"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_TLM].error_counter)"
desc = "地上局コマンド実行異常カウンタ"

[[tlm_field]]
name = "TLC_TLM.SOE_FLAG"
type = "uint8_t"
exp = "(uint8_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_TLM].stop_on_error)"
status = "2.12"

[[tlm_field]]
name = "TLC_TLM.LOCKOUT_FLAG"
type = "uint8_t"
exp = "(uint8_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_DEPLOY_TLM].lockout)"
status = "2.13"

[[tlm_field]]
name = "TLC_TLM.NEXT_TIME"
type = "uint32_t"
exp = "(PL_is_empty(&(PH_tl_cmd_list[TLCD_ID_DEPLOY_TLM])) ? 0 : (uint32_t)CCP_get_ti((const CommonCmdPacket*)(PL_get_head(&(PH_tl_cmd_list[TLCD_ID_DEPLOY_TLM]))->packet)))"
desc = "次TL1コマンド実行時刻"
note = "変数指定が大変なことに…"

[[tlm_field]]
name = "TLC_TLM.NEXT_ID"
type = "uint16_t"
exp = "(uint16_t)(PL_is_empty(&(PH_tl_cmd_list[TLCD_ID_DEPLOY_TLM])) ? 0 : CCP_get_id((const CommonCmdPacket*)(PL_get_head(&(PH_tl_cmd_list[TLCD_ID_DEPLOY_TLM]))->packet)))"
desc = "次TL1コマンドID"
note = "変数指定が大変なことに…"

[[tlm_field]]
name = "TLC_MIS.COUNTER"
type = "uint32_t"
exp = "PL_count_executed_nodes(&PH_tl_cmd_list[TLCD_ID_FROM_GS_FOR_MISSION])"
desc = "TL0コマンドカウンタ"

[[tlm_field]]
name = "TLC_MIS.QUEUED"
type = "uint8_t"
exp = "(uint8_t)(PL_count_active_nodes(&PH_tl_cmd_list[TLCD_ID_FROM_GS_FOR_MISSION]))"
desc = "TL0登録コマンド数"

[[tlm_field]]
name = "TLC_MIS.LAST_EXEC_TIME"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS_FOR_MISSION].prev.time.total_cycle)"
desc = "最新TL0コマンド実行時刻"

[[tlm_field]]
name = "TLC_MIS.LAST_EXEC_ID"
type = "uint16_t"
exp = "(uint16_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS_FOR_MISSION].prev.code)"
desc = "最新TL0コマンドID"

[[tlm_field]]
name = "TLC_MIS.LAST_EXEC_STS"
type = "int32_t"
exp = "(int32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS_FOR_MISSION].prev.sts)"
status = "7.1"
desc = "最新TL0コマンド実行結果"

[[tlm_field]]
name = "TLC_MIS.LAST_ERR_TIME"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS_FOR_MISSION].prev_err.time.total_cycle)"
desc = "最新TL0コマンド実行時刻"

[[tlm_field]]
name = "TLC_MIS.LAST_ERR_ID"
type = "uint16_t"
exp = "(uint16_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS_FOR_MISSION].prev_err.code)"
desc = "最新TL0コマンドID"

[[tlm_field]]
name = "TLC_MIS.LAST_ERR_STS"
type = "int32_t"
exp = "(int32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS_FOR_MISSION].prev_err.sts)"
status = "7.1"
desc = "最新TL0コマンド実行結果"

[[tlm_field]]
name = "TLC_MIS.ERR_COUNTER"
type = "uint32_t"
exp = "(uint32_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS_FOR_MISSION].error_counter)"
desc = "地上局コマンド実行異常カウンタ"

[[tlm_field]]
name = "TLC_MIS.SOE_FLAG"
type = "uint8_t"
exp = "(uint8_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS_FOR_MISSION].stop_on_error)"
status = "2.12"

[[tlm_field]]
name = "TLC_MIS.LOCKOUT_FLAG"
type = "uint8_t"
exp = "(uint8_t)(timeline_command_dispatcher->dispatcher[TLCD_ID_FROM_GS_FOR_MISSION].lockout)"
status = "2.13"

[[tlm_field]]
name = "TLC_MIS.NEXT_TIME"
type = "uint32_t"
exp = "(PL_is_empty(&(PH_tl_cmd_list[TLCD_ID_FROM_GS_FOR_MISSION])) ? 0 : (uint32_t)CCP_get_ti((const CommonCmdPacket*)(PL_get_head(&(PH_tl_cmd_list[TLCD_ID_FROM_GS_FOR_MISSION]))->packet)))"
desc = "次TL0コマンド実行時刻"
note = "変数指定が大変なことに…"

[[tlm_field]]
name = "TLC_MIS.NEXT_ID"
type = "uint16_t"
exp = "(uint16_t)(PL_is_empty(&(PH_tl_cmd_list[TLCD_ID_FROM_GS_FOR_MISSION])) ? 0 : CCP_get_id((const CommonCmdPacket*)(PL_get_head(&(PH_tl_cmd_list[TLCD_ID_FROM_GS_FOR_MISSION]))->packet)))"
desc = "次TL0コマンドID"
note = "変数指定が大変なことに…"

[[tlm_field]]
name = "BCT_BLK_PTR"
type = "uint8_t"
exp = "(uint8_t)(block_command_table->pos.block)"
desc = "BCT ブロックポインタ"

[[tlm_field]]
name = "BCT_CMD_PTR"
type = "uint8_t"
exp = "(uint8_t)(block_command_table->pos.cmd)"
desc = "BCT コマンドポインタ"

[[tlm_field]]
name = "BCT_REGD_TIME"
type = "uint32_t"
exp = "((block_command_table->pos.cmd == 0) ? 0 : (uint32_t)BCT_get_ti(block_command_table->pos.block@@ (uint8_t)(block_command_table->pos.cmd-1)))"
desc = "BCT 登録コマンド時刻"
note = "変数指定が大変なことに…"

[[tlm_field]]
name = "BCT_REGD_ID"
type = "uint16_t"
exp = "(uint16_t)((block_command_table->pos.cmd == 0) ? 0 : BCT_get_id(block_command_table->pos.block@@ (uint8_t)(block_command_table->pos.cmd-1)))"
desc = "BCT 登録コマンドID"
note = "変数指定が大変なことに…"

[[tlm_field]]
name = "MS_BUFFER_AVAILABLE"
type = "uint8_t"
exp = "gs_driver->ccsds_info.buffer_num"
desc = "CCSDS MS VCDU 使用量"

[[tlm_field]]
name = "MS_T2M_FLUSH_INTERVAL"
type = "uint32_t"
exp = "(uint32_t)(DI_GS_ms_tlm_packet_handler->tc_packet_to_m_pdu.flush_interval)"
desc = "TL0コマンドカウンタ"

[[tlm_field]]
name = "RP_T2M_FLUSH_INTERVAL"
type = "uint32_t"
exp = "(uint32_t)(DI_GS_rp_tlm_packet_handler->tc_packet_to_m_pdu.flush_interval)"
desc = "TL0コマンドカウンタ"

[[tlm_field]]
name = "MS_TLM_COUNTER"
type = "uint32_t"
exp = "PL_count_executed_nodes(&PH_ms_tlm_list)"
desc = "TL0コマンドカウンタ"

[[tlm_field]]
name = "MS_TLM_QUEUED"
type = "uint8_t"
exp = "(uint8_t)(PL_count_active_nodes(&PH_ms_tlm_list))"
desc = "TL0登録コマンド数"

[[tlm_field]]
name = "ST_TLM_COUNTER"
type = "uint32_t"
exp = "PL_count_executed_nodes(&PH_st_tlm_list)"
desc = "TL0コマンドカウンタ"

[[tlm_field]]
name = "ST_TLM_QUEUED"
type = "uint8_t"
exp = "(uint8_t)(PL_count_active_nodes(&PH_st_tlm_list))"
desc = "TL0登録コマンド数"

[[tlm_field]]
name = "RP_TLM_COUNTER"
type = "uint32_t"
exp = "PL_count_executed_nodes(&PH_rp_tlm_list)"
desc = "TL0コマンドカウンタ"

[[tlm_field]]
name = "RP_TLM_QUEUED"
type = "uint8_t"
exp = "(uint8_t)(PL_count_active_nodes(&PH_rp_tlm_list))"
desc = "TL0登録コマンド数"

[[tlm_field]]
name = "TCI_TX_CYCLE"
type = "uint32_t"
exp = "(uint32_t)gs_driver->latest_info->tx.send_cycle"
desc = "時刻校正情報::送出サイクル"

[[tlm_field]]
name = "TCI_TX_BITRATE"
type = "uint32_t"
exp = "gs_driver->driver_ccsds.ccsds_config.bitrate"
desc = "時刻校正情報::送出ビットレート"

[[tlm_field]]
name = "TCI_VCID"
type = "uint8_t"
exp = "(uint8_t)gs_driver->latest_info->tx.vcid"
desc = "時刻構成情報::送出VCID"

[[tlm_field]]
name = "TCI_VCDU_COUNTER"
type = "uint32_t"
exp = "gs_driver->latest_info->tx.vcdu_counter"
desc = "時刻校正情報::送出VCDUカウンタ"

