obc = "MOBC"
Target = "OBC"
PacketID = "0x10"
"Enable/Disable" = "ENABLE"
IsRestricted = "FALSE"
"Local Var" = ""

[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.VER"
bitlen = 3
[[tlm_field.comp]]
name = "PH.TYPE"
bitlen = 1
[[tlm_field.comp]]
name = "PH.SH_FLAG"
bitlen = 1
[[tlm_field.comp]]
name = "PH.APID"
bitlen = 11


[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.SEQ_FLAG"
bitlen = 2
[[tlm_field.comp]]
name = "PH.SEQ_COUNT"
bitlen = 14


[[tlm_field]]
name = "PH.PACKET_LEN"
type = "uint16_t"

[[tlm_field]]
name = "SH.VER"
type = "uint8_t"

[[tlm_field]]
name = "SH.TI"
type = "uint32_t"

[[tlm_field]]
name = "SH.TLM_ID"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.GLOBAL_TIME"
type = "double"

[[tlm_field]]
name = "SH.ON_BOARD_SUBNET_TIME"
type = "uint32_t"

[[tlm_field]]
name = "SH.DEST_FLAGS"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.DR_PARTITION"
type = "uint8_t"

[[tlm_field]]
name = "MEM.BEGIN"
type = "uint32_t"
exp = "memory_dump->begin"
is_hex = true
desc = "メモリ操作領域開始アドレス"

[[tlm_field]]
name = "MEM.END"
type = "uint32_t"
exp = "memory_dump->end"
is_hex = true
desc = "メモリ操作領域終端アドレス"

[[tlm_field]]
name = "MEM.ADU_SIZE"
type = "uint32_t"
exp = "memory_dump->adu_size"
desc = "メモリ操作領域サイズ = ADUサイズ"
note = "CCSDSパケットヘッダに設定される"

[[tlm_field]]
name = "MEM.ADU_SEQ"
type = "uint16_t"
exp = "memory_dump->adu_seq"
desc = "ADUシーケンスカウンタ"
note = "CCSDSパケットヘッダに設定される"

[[tlm_field]]
name = "MEM.ADU_COUNTER"
type = "uint8_t"
exp = "memory_dump->adu_counter"
desc = "ADUカウンタ"
note = "CCSDSパケットヘッダに設定される"

[[tlm_field]]
name = "MEM.DESTINATION"
type = "uint32_t"
exp = "memory_dump->dest"
is_hex = true
desc = "コピー先アドレス"

[[tlm_field]]
name = "MEM.RP"
type = "uint32_t"
exp = "memory_dump->rp"
is_hex = true
desc = "コーピー用RP"

