obc = "MOBC"
Target = "OBC"
PacketID = "0x57"
"Enable/Disable" = "ENABLE"
IsRestricted = "FALSE"
"Local Var" = "EL_ERROR_LEVEL err_level = event_logger->tlm_info.tlog.err_level;##uint16_t offset = EL_TLOG_TLM_PAGE_SIZE * event_logger->tlm_info.tlog.page_no;##const EL_Event* events = event_logger->tlogs[err_level].events;##"

[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.VER"
bitlen = 3
[[tlm_field.comp]]
name = "PH.TYPE"
bitlen = 1
[[tlm_field.comp]]
name = "PH.SH_FLAG"
bitlen = 1
[[tlm_field.comp]]
name = "PH.APID"
bitlen = 11


[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.SEQ_FLAG"
bitlen = 2
[[tlm_field.comp]]
name = "PH.SEQ_COUNT"
bitlen = 14


[[tlm_field]]
name = "PH.PACKET_LEN"
type = "uint16_t"

[[tlm_field]]
name = "SH.VER"
type = "uint8_t"

[[tlm_field]]
name = "SH.TI"
type = "uint32_t"

[[tlm_field]]
name = "SH.TLM_ID"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.GLOBAL_TIME"
type = "double"

[[tlm_field]]
name = "SH.ON_BOARD_SUBNET_TIME"
type = "uint32_t"

[[tlm_field]]
name = "SH.DEST_FLAGS"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.DR_PARTITION"
type = "uint8_t"

[[tlm_field]]
name = "TLM_INFO.TLOG.PAGE_NO"
type = "uint8_t"
exp = "event_logger->tlm_info.tlog.page_no"

[[tlm_field]]
type = "uint8_t"
[[tlm_field.comp]]
name = "TLM_INFO.TLOG.ERR_LEVEL"
bitlen = 4
exp = "(uint8_t)((err_level << 4 & 0xf0) | (event_logger->tlogs[err_level].is_enable_overwrite << 3 & 0x08) | ( event_logger->tlogs[err_level].is_table_overflow << 2 & 0x04))"
status = "5.1"
[[tlm_field.comp]]
name = "TLOGS.IS_ENABLE_OVERWRITE"
bitlen = 1
exp = "err_level"
[[tlm_field.comp]]
name = "TLOGS.IS_TABLE_OVERFLOW"
bitlen = 1
exp = "event_logger->tlogs[err_level].is_enable_overwrite"
[[tlm_field.comp]]
name = "TLOGS.DUMMY"
bitlen = 2
exp = "event_logger->tlogs[err_level].is_table_overflow"


[[tlm_field]]
name = "STATISTICS.RECORD_COUNTER_TOTAL"
type = "uint32_t"
exp = "event_logger->statistics.record_counter_total"

[[tlm_field]]
name = "STATISTICS.RECORD_COUNTERS_ERR_LEVEL"
type = "uint32_t"
exp = "event_logger->statistics.record_counters[err_level]"

[[tlm_field]]
name = "TLOGS.LOG_CAPACITY"
type = "uint16_t"
exp = "event_logger->tlogs[err_level].log_capacity"

[[tlm_field]]
name = "TLOGS.LOG_WP"
type = "uint16_t"
exp = "event_logger->tlogs[err_level].log_wp"

[[tlm_field]]
name = "TLOGS.EVENTS0.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+0].group"

[[tlm_field]]
name = "TLOGS.EVENTS0.LOCAL"
type = "uint32_t"
exp = "events[offset+0].local"

[[tlm_field]]
name = "TLOGS.EVENTS0.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+0].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS0.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+0].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS0.NOTE"
type = "uint32_t"
exp = "events[offset+0].note"

[[tlm_field]]
name = "TLOGS.EVENTS1.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+1].group"

[[tlm_field]]
name = "TLOGS.EVENTS1.LOCAL"
type = "uint32_t"
exp = "events[offset+1].local"

[[tlm_field]]
name = "TLOGS.EVENTS1.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+1].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS1.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+1].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS1.NOTE"
type = "uint32_t"
exp = "events[offset+1].note"

[[tlm_field]]
name = "TLOGS.EVENTS2.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+2].group"

[[tlm_field]]
name = "TLOGS.EVENTS2.LOCAL"
type = "uint32_t"
exp = "events[offset+2].local"

[[tlm_field]]
name = "TLOGS.EVENTS2.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+2].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS2.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+2].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS2.NOTE"
type = "uint32_t"
exp = "events[offset+2].note"

[[tlm_field]]
name = "TLOGS.EVENTS3.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+3].group"

[[tlm_field]]
name = "TLOGS.EVENTS3.LOCAL"
type = "uint32_t"
exp = "events[offset+3].local"

[[tlm_field]]
name = "TLOGS.EVENTS3.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+3].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS3.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+3].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS3.NOTE"
type = "uint32_t"
exp = "events[offset+3].note"

[[tlm_field]]
name = "TLOGS.EVENTS4.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+4].group"

[[tlm_field]]
name = "TLOGS.EVENTS4.LOCAL"
type = "uint32_t"
exp = "events[offset+4].local"

[[tlm_field]]
name = "TLOGS.EVENTS4.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+4].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS4.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+4].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS4.NOTE"
type = "uint32_t"
exp = "events[offset+4].note"

[[tlm_field]]
name = "TLOGS.EVENTS5.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+5].group"

[[tlm_field]]
name = "TLOGS.EVENTS5.LOCAL"
type = "uint32_t"
exp = "events[offset+5].local"

[[tlm_field]]
name = "TLOGS.EVENTS5.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+5].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS5.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+5].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS5.NOTE"
type = "uint32_t"
exp = "events[offset+5].note"

[[tlm_field]]
name = "TLOGS.EVENTS6.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+6].group"

[[tlm_field]]
name = "TLOGS.EVENTS6.LOCAL"
type = "uint32_t"
exp = "events[offset+6].local"

[[tlm_field]]
name = "TLOGS.EVENTS6.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+6].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS6.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+6].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS6.NOTE"
type = "uint32_t"
exp = "events[offset+6].note"

[[tlm_field]]
name = "TLOGS.EVENTS7.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+7].group"

[[tlm_field]]
name = "TLOGS.EVENTS7.LOCAL"
type = "uint32_t"
exp = "events[offset+7].local"

[[tlm_field]]
name = "TLOGS.EVENTS7.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+7].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS7.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+7].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS7.NOTE"
type = "uint32_t"
exp = "events[offset+7].note"

[[tlm_field]]
name = "TLOGS.EVENTS8.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+8].group"

[[tlm_field]]
name = "TLOGS.EVENTS8.LOCAL"
type = "uint32_t"
exp = "events[offset+8].local"

[[tlm_field]]
name = "TLOGS.EVENTS8.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+8].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS8.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+8].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS8.NOTE"
type = "uint32_t"
exp = "events[offset+8].note"

[[tlm_field]]
name = "TLOGS.EVENTS9.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+9].group"

[[tlm_field]]
name = "TLOGS.EVENTS9.LOCAL"
type = "uint32_t"
exp = "events[offset+9].local"

[[tlm_field]]
name = "TLOGS.EVENTS9.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+9].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS9.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+9].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS9.NOTE"
type = "uint32_t"
exp = "events[offset+9].note"

[[tlm_field]]
name = "TLOGS.EVENTS10.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+10].group"

[[tlm_field]]
name = "TLOGS.EVENTS10.LOCAL"
type = "uint32_t"
exp = "events[offset+10].local"

[[tlm_field]]
name = "TLOGS.EVENTS10.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+10].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS10.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+10].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS10.NOTE"
type = "uint32_t"
exp = "events[offset+10].note"

[[tlm_field]]
name = "TLOGS.EVENTS11.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+11].group"

[[tlm_field]]
name = "TLOGS.EVENTS11.LOCAL"
type = "uint32_t"
exp = "events[offset+11].local"

[[tlm_field]]
name = "TLOGS.EVENTS11.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+11].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS11.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+11].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS11.NOTE"
type = "uint32_t"
exp = "events[offset+11].note"

[[tlm_field]]
name = "TLOGS.EVENTS12.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+12].group"

[[tlm_field]]
name = "TLOGS.EVENTS12.LOCAL"
type = "uint32_t"
exp = "events[offset+12].local"

[[tlm_field]]
name = "TLOGS.EVENTS12.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+12].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS12.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+12].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS12.NOTE"
type = "uint32_t"
exp = "events[offset+12].note"

[[tlm_field]]
name = "TLOGS.EVENTS13.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+13].group"

[[tlm_field]]
name = "TLOGS.EVENTS13.LOCAL"
type = "uint32_t"
exp = "events[offset+13].local"

[[tlm_field]]
name = "TLOGS.EVENTS13.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+13].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS13.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+13].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS13.NOTE"
type = "uint32_t"
exp = "events[offset+13].note"

[[tlm_field]]
name = "TLOGS.EVENTS14.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+14].group"

[[tlm_field]]
name = "TLOGS.EVENTS14.LOCAL"
type = "uint32_t"
exp = "events[offset+14].local"

[[tlm_field]]
name = "TLOGS.EVENTS14.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+14].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS14.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+14].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS14.NOTE"
type = "uint32_t"
exp = "events[offset+14].note"

[[tlm_field]]
name = "TLOGS.EVENTS15.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+15].group"

[[tlm_field]]
name = "TLOGS.EVENTS15.LOCAL"
type = "uint32_t"
exp = "events[offset+15].local"

[[tlm_field]]
name = "TLOGS.EVENTS15.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+15].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS15.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+15].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS15.NOTE"
type = "uint32_t"
exp = "events[offset+15].note"

[[tlm_field]]
name = "TLOGS.EVENTS16.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+16].group"

[[tlm_field]]
name = "TLOGS.EVENTS16.LOCAL"
type = "uint32_t"
exp = "events[offset+16].local"

[[tlm_field]]
name = "TLOGS.EVENTS16.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+16].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS16.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+16].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS16.NOTE"
type = "uint32_t"
exp = "events[offset+16].note"

[[tlm_field]]
name = "TLOGS.EVENTS17.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+17].group"

[[tlm_field]]
name = "TLOGS.EVENTS17.LOCAL"
type = "uint32_t"
exp = "events[offset+17].local"

[[tlm_field]]
name = "TLOGS.EVENTS17.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+17].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS17.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+17].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS17.NOTE"
type = "uint32_t"
exp = "events[offset+17].note"

[[tlm_field]]
name = "TLOGS.EVENTS18.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+18].group"

[[tlm_field]]
name = "TLOGS.EVENTS18.LOCAL"
type = "uint32_t"
exp = "events[offset+18].local"

[[tlm_field]]
name = "TLOGS.EVENTS18.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+18].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS18.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+18].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS18.NOTE"
type = "uint32_t"
exp = "events[offset+18].note"

[[tlm_field]]
name = "TLOGS.EVENTS19.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+19].group"

[[tlm_field]]
name = "TLOGS.EVENTS19.LOCAL"
type = "uint32_t"
exp = "events[offset+19].local"

[[tlm_field]]
name = "TLOGS.EVENTS19.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+19].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS19.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+19].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS19.NOTE"
type = "uint32_t"
exp = "events[offset+19].note"

[[tlm_field]]
name = "TLOGS.EVENTS20.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+20].group"

[[tlm_field]]
name = "TLOGS.EVENTS20.LOCAL"
type = "uint32_t"
exp = "events[offset+20].local"

[[tlm_field]]
name = "TLOGS.EVENTS20.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+20].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS20.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+20].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS20.NOTE"
type = "uint32_t"
exp = "events[offset+20].note"

[[tlm_field]]
name = "TLOGS.EVENTS21.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+21].group"

[[tlm_field]]
name = "TLOGS.EVENTS21.LOCAL"
type = "uint32_t"
exp = "events[offset+21].local"

[[tlm_field]]
name = "TLOGS.EVENTS21.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+21].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS21.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+21].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS21.NOTE"
type = "uint32_t"
exp = "events[offset+21].note"

[[tlm_field]]
name = "TLOGS.EVENTS22.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+22].group"

[[tlm_field]]
name = "TLOGS.EVENTS22.LOCAL"
type = "uint32_t"
exp = "events[offset+22].local"

[[tlm_field]]
name = "TLOGS.EVENTS22.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+22].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS22.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+22].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS22.NOTE"
type = "uint32_t"
exp = "events[offset+22].note"

[[tlm_field]]
name = "TLOGS.EVENTS23.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+23].group"

[[tlm_field]]
name = "TLOGS.EVENTS23.LOCAL"
type = "uint32_t"
exp = "events[offset+23].local"

[[tlm_field]]
name = "TLOGS.EVENTS23.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+23].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS23.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+23].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS23.NOTE"
type = "uint32_t"
exp = "events[offset+23].note"

[[tlm_field]]
name = "TLOGS.EVENTS24.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+24].group"

[[tlm_field]]
name = "TLOGS.EVENTS24.LOCAL"
type = "uint32_t"
exp = "events[offset+24].local"

[[tlm_field]]
name = "TLOGS.EVENTS24.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+24].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS24.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+24].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS24.NOTE"
type = "uint32_t"
exp = "events[offset+24].note"

[[tlm_field]]
name = "TLOGS.EVENTS25.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+25].group"

[[tlm_field]]
name = "TLOGS.EVENTS25.LOCAL"
type = "uint32_t"
exp = "events[offset+25].local"

[[tlm_field]]
name = "TLOGS.EVENTS25.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+25].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS25.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+25].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS25.NOTE"
type = "uint32_t"
exp = "events[offset+25].note"

[[tlm_field]]
name = "TLOGS.EVENTS26.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+26].group"

[[tlm_field]]
name = "TLOGS.EVENTS26.LOCAL"
type = "uint32_t"
exp = "events[offset+26].local"

[[tlm_field]]
name = "TLOGS.EVENTS26.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+26].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS26.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+26].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS26.NOTE"
type = "uint32_t"
exp = "events[offset+26].note"

[[tlm_field]]
name = "TLOGS.EVENTS27.GROUP"
type = "uint8_t"
exp = "(uint8_t)events[offset+27].group"

[[tlm_field]]
name = "TLOGS.EVENTS27.LOCAL"
type = "uint32_t"
exp = "events[offset+27].local"

[[tlm_field]]
name = "TLOGS.EVENTS27.TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "events[offset+27].time.total_cycle"

[[tlm_field]]
name = "TLOGS.EVENTS27.TIME.STEP"
type = "uint8_t"
exp = "(uint8_t)events[offset+27].time.step"

[[tlm_field]]
name = "TLOGS.EVENTS27.NOTE"
type = "uint32_t"
exp = "events[offset+27].note"

