obc = "MOBC"
Target = "OBC"
PacketID = "0x5a"
"Enable/Disable" = "ENABLE"
IsRestricted = "FALSE"
"Local Var" = ""

[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.VER"
bitlen = 3
[[tlm_field.comp]]
name = "PH.TYPE"
bitlen = 1
[[tlm_field.comp]]
name = "PH.SH_FLAG"
bitlen = 1
[[tlm_field.comp]]
name = "PH.APID"
bitlen = 11


[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.SEQ_FLAG"
bitlen = 2
[[tlm_field.comp]]
name = "PH.SEQ_COUNT"
bitlen = 14


[[tlm_field]]
name = "PH.PACKET_LEN"
type = "uint16_t"

[[tlm_field]]
name = "SH.VER"
type = "uint8_t"

[[tlm_field]]
name = "SH.TI"
type = "uint32_t"

[[tlm_field]]
name = "SH.TLM_ID"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.GLOBAL_TIME"
type = "double"

[[tlm_field]]
name = "SH.ON_BOARD_SUBNET_TIME"
type = "uint32_t"

[[tlm_field]]
name = "SH.DEST_FLAGS"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.DR_PARTITION"
type = "uint8_t"

[[tlm_field]]
name = "EVENT_UTIL.IS_ENABLED_EH_EXECUTION"
type = "uint8_t"
exp = "event_utility->is_enabled_eh_execution"
status = "2.14"

[[tlm_field]]
name = "EL_EVENT_COUNTER.COUNTER_TOTAL"
type = "uint32_t"
exp = "event_handler->el_event_counter.counter_total"

[[tlm_field]]
name = "EL_EVENT_COUNTER.COUNTERS.EL_ERROR_LEVEL_HIGH"
type = "uint32_t"
exp = "event_handler->el_event_counter.counters[EL_ERROR_LEVEL_HIGH]"

[[tlm_field]]
name = "EL_EVENT_COUNTER.COUNTERS.EL_ERROR_LEVEL_MIDDLE"
type = "uint32_t"
exp = "event_handler->el_event_counter.counters[EL_ERROR_LEVEL_MIDDLE]"

[[tlm_field]]
name = "EL_EVENT_COUNTER.COUNTERS.EL_ERROR_LEVEL_LOW"
type = "uint32_t"
exp = "event_handler->el_event_counter.counters[EL_ERROR_LEVEL_LOW]"

[[tlm_field]]
name = "EL_EVENT_COUNTER.COUNTERS.EL_ERROR_LEVEL_EL"
type = "uint32_t"
exp = "event_handler->el_event_counter.counters[EL_ERROR_LEVEL_EL]"

[[tlm_field]]
name = "EL_EVENT_COUNTER.COUNTERS.EL_ERROR_LEVEL_EH"
type = "uint32_t"
exp = "event_handler->el_event_counter.counters[EL_ERROR_LEVEL_EH]"

[[tlm_field]]
name = "LOG_TABLE.RESPOND_COUNTER"
type = "uint32_t"
exp = "event_handler->log_table.respond_counter"

[[tlm_field]]
name = "LOG_TABLE.LOG_WP"
type = "uint16_t"
exp = "event_handler->log_table.log_wp"

[[tlm_field]]
name = "EXEC_SETTINGS.MAX_RESPONSE_NUM"
type = "uint8_t"
exp = "event_handler->exec_settings.max_response_num"

[[tlm_field]]
name = "EXEC_SETTINGS.MAX_CHECK_EVENT_NUM"
type = "uint16_t"
exp = "event_handler->exec_settings.max_check_event_num"

[[tlm_field]]
name = "EXEC_SETTINGS.MAX_MULTI_LEVEL_NUM"
type = "uint8_t"
exp = "event_handler->exec_settings.max_multi_level_num"

[[tlm_field]]
name = "REG_FROM_CMD.RULE_ID"
type = "uint8_t"
exp = "(uint8_t)event_handler->reg_from_cmd.rule_id"

[[tlm_field]]
name = "REG_FROM_CMD.SETTINGS.EVENT.GROUP"
type = "uint8_t"
exp = "(uint8_t)event_handler->reg_from_cmd.settings.event.group"

[[tlm_field]]
name = "REG_FROM_CMD.SETTINGS.EVENT.LOCAL"
type = "uint32_t"
exp = "event_handler->reg_from_cmd.settings.event.local"

[[tlm_field]]
type = "uint8_t"
[[tlm_field.comp]]
name = "REG_FROM_CMD.SETTINGS.EVENT.ERR_LEVEL"
bitlen = 3
exp = "(uint8_t)((((uint8_t)event_handler->reg_from_cmd.settings.event.err_level) << 5 & 0xe0) | (event_handler->reg_from_cmd.settings.should_match_err_level << 4 & 0x10) | (event_handler->reg_from_cmd.settings.is_active << 3 & 0x08) | (((uint8_t)event_handler->reg_from_cmd.settings.condition.type) & 0x07))"
status = "5.1"
[[tlm_field.comp]]
name = "REG_FROM_CMD.SETTINGS.SHOULD_MATCH_ERR_LEVEL"
bitlen = 1
exp = "(uint8_t)event_handler->reg_from_cmd.settings.event.err_level"
status = "2.5"
[[tlm_field.comp]]
name = "REG_FROM_CMD.SETTINGS.IS_ACTIVE"
bitlen = 1
exp = "event_handler->reg_from_cmd.settings.should_match_err_level"
status = "2.6"
[[tlm_field.comp]]
name = "REG_FROM_CMD.SETTINGS.CONDITION.TYPE"
bitlen = 3
exp = "event_handler->reg_from_cmd.settings.is_active"
status = "3.1"
note = "1 bitあまりあり"


[[tlm_field]]
name = "REG_FROM_CMD.SETTINGS.CONDITION.COUNT_THRESHOLD"
type = "uint16_t"
exp = "event_handler->reg_from_cmd.settings.condition.count_threshold"

[[tlm_field]]
name = "REG_FROM_CMD.SETTINGS.CONDITION.TIME_THRESHOLD_MS"
type = "uint32_t"
exp = "event_handler->reg_from_cmd.settings.condition.time_threshold_ms"

[[tlm_field]]
name = "REG_FROM_CMD.SETTINGS.DEPLOY_BCT_ID"
type = "uint16_t"
exp = "(uint16_t)event_handler->reg_from_cmd.settings.deploy_bct_id"

[[tlm_field]]
name = "REG_FROM_CMD.REGISTER_ACK"
type = "uint8_t"
exp = "(uint8_t)event_handler->reg_from_cmd.register_ack"

[[tlm_field]]
name = "TLM_INFO.RULE.PAGE_NO"
type = "uint8_t"
exp = "event_handler->tlm_info.rule.page_no"

[[tlm_field]]
name = "TLM_INFO.RULE.TARGET_RULE_ID"
type = "uint8_t"
exp = "(uint8_t)event_handler->tlm_info.rule.target_rule_id"

[[tlm_field]]
name = "TLM_INFO.RULE_SORTED_INDEX.PAGE_NO"
type = "uint8_t"
exp = "event_handler->tlm_info.rule_sorted_index.page_no"

[[tlm_field]]
name = "TLM_INFO.LOG.PAGE_NO"
type = "uint8_t"
exp = "event_handler->tlm_info.log.page_no"

[[tlm_field]]
name = "TARTGET_RULE.SETTINGS.EVENT.GROUP"
type = "uint8_t"
exp = "(uint8_t)event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.event.group"

[[tlm_field]]
name = "TARTGET_RULE.SETTINGS.EVENT.LOCAL"
type = "uint32_t"
exp = "event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.event.local"

[[tlm_field]]
type = "uint8_t"
[[tlm_field.comp]]
name = "TARTGET_RULE.SETTINGS.EVENT.ERR_LEVEL"
bitlen = 3
exp = "(uint8_t)((((uint8_t)event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.event.err_level) << 5 & 0xe0) | (event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.should_match_err_level << 4 & 0x10) | (event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.is_active << 3 & 0x08) | (((uint8_t)event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.condition.type) & 0x07))"
status = "5.1"
[[tlm_field.comp]]
name = "TARTGET_RULE.SETTINGS.SHOULD_MATCH_ERR_LEVEL"
bitlen = 1
exp = "(uint8_t)event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.event.err_level"
status = "2.5"
[[tlm_field.comp]]
name = "TARTGET_RULE.SETTINGS.IS_ACTIVE"
bitlen = 1
exp = "event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.should_match_err_level"
status = "2.6"
[[tlm_field.comp]]
name = "TARTGET_RULE.SETTINGS.CONDITION.TYPE"
bitlen = 3
exp = "event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.is_active"
status = "3.1"
note = "1 bitあまりあり"


[[tlm_field]]
name = "TARTGET_RULE.SETTINGS.CONDITION.COUNT_THRESHOLD"
type = "uint16_t"
exp = "event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.condition.count_threshold"

[[tlm_field]]
name = "TARTGET_RULE.SETTINGS.CONDITION.TIME_THRESHOLD_MS"
type = "uint32_t"
exp = "event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.condition.time_threshold_ms"

[[tlm_field]]
name = "TARTGET_RULE.SETTINGS.DEPLOY_BCT_ID"
type = "uint16_t"
exp = "(uint16_t)event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].settings.deploy_bct_id"

[[tlm_field]]
name = "TARTGET_RULE.COUNTER"
type = "uint16_t"
exp = "event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].counter"

[[tlm_field]]
name = "TARTGET_RULE.LAST_EVENT_TIME.TOTAL_CYCLE"
type = "uint32_t"
exp = "(uint32_t)event_handler->rule_table.rules[event_handler->tlm_info.rule.target_rule_id].last_event_time.total_cycle"

