obc = "MOBC"
Target = "OBC"
PacketID = "0xf1"
"Enable/Disable" = "ENABLE"
IsRestricted = "FALSE"
"Local Var" = ""

[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.VER"
bitlen = 3
[[tlm_field.comp]]
name = "PH.TYPE"
bitlen = 1
[[tlm_field.comp]]
name = "PH.SH_FLAG"
bitlen = 1
[[tlm_field.comp]]
name = "PH.APID"
bitlen = 11


[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.SEQ_FLAG"
bitlen = 2
[[tlm_field.comp]]
name = "PH.SEQ_COUNT"
bitlen = 14


[[tlm_field]]
name = "PH.PACKET_LEN"
type = "uint16_t"

[[tlm_field]]
name = "SH.VER"
type = "uint8_t"

[[tlm_field]]
name = "SH.TI"
type = "uint32_t"

[[tlm_field]]
name = "SH.TLM_ID"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.GLOBAL_TIME"
type = "double"

[[tlm_field]]
name = "SH.ON_BOARD_SUBNET_TIME"
type = "uint32_t"

[[tlm_field]]
name = "SH.DEST_FLAGS"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.DR_PARTITION"
type = "uint8_t"

[[tlm_field]]
name = "CORE0"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[0]"
is_hex = true

[[tlm_field]]
name = "CORE1"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[1]"
is_hex = true

[[tlm_field]]
name = "CORE2"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[2]"
is_hex = true

[[tlm_field]]
name = "CORE3"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[3]"
is_hex = true

[[tlm_field]]
name = "CORE4"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[4]"
is_hex = true

[[tlm_field]]
name = "CORE5"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[5]"
is_hex = true

[[tlm_field]]
name = "CORE6"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[6]"
is_hex = true

[[tlm_field]]
name = "CORE7"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[7]"
is_hex = true

[[tlm_field]]
name = "CORE8"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[8]"
is_hex = true

[[tlm_field]]
name = "CORE9"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[9]"
is_hex = true

[[tlm_field]]
name = "CORE10"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[10]"
is_hex = true

[[tlm_field]]
name = "CORE11"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[11]"
is_hex = true

[[tlm_field]]
name = "CORE12"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[12]"
is_hex = true

[[tlm_field]]
name = "CORE13"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[13]"
is_hex = true

[[tlm_field]]
name = "CORE14"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[14]"
is_hex = true

[[tlm_field]]
name = "CORE15"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[15]"
is_hex = true

[[tlm_field]]
name = "CORE16"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[16]"
is_hex = true

[[tlm_field]]
name = "CORE17"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[17]"
is_hex = true

[[tlm_field]]
name = "CORE18"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[18]"
is_hex = true

[[tlm_field]]
name = "CORE19"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[19]"
is_hex = true

[[tlm_field]]
name = "CORE20"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[20]"
is_hex = true

[[tlm_field]]
name = "CORE21"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[21]"
is_hex = true

[[tlm_field]]
name = "CORE22"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[22]"
is_hex = true

[[tlm_field]]
name = "CORE23"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[23]"
is_hex = true

[[tlm_field]]
name = "CORE24"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[24]"
is_hex = true

[[tlm_field]]
name = "CORE25"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[25]"
is_hex = true

[[tlm_field]]
name = "CORE26"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[26]"
is_hex = true

[[tlm_field]]
name = "CORE27"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[27]"
is_hex = true

[[tlm_field]]
name = "CORE28"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[28]"
is_hex = true

[[tlm_field]]
name = "CORE29"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[29]"
is_hex = true

[[tlm_field]]
name = "CORE30"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[30]"
is_hex = true

[[tlm_field]]
name = "CORE31"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[31]"
is_hex = true

[[tlm_field]]
name = "CORE32"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[32]"
is_hex = true

[[tlm_field]]
name = "CORE33"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[33]"
is_hex = true

[[tlm_field]]
name = "CORE34"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[34]"
is_hex = true

[[tlm_field]]
name = "CORE35"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[35]"
is_hex = true

[[tlm_field]]
name = "CORE36"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[36]"
is_hex = true

[[tlm_field]]
name = "CORE37"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[37]"
is_hex = true

[[tlm_field]]
name = "CORE38"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[38]"
is_hex = true

[[tlm_field]]
name = "CORE39"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[39]"
is_hex = true

[[tlm_field]]
name = "CORE40"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_CORE[40]"
is_hex = true

[[tlm_field]]
name = "USER0"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[0]"
is_hex = true

[[tlm_field]]
name = "USER1"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[1]"
is_hex = true

[[tlm_field]]
name = "USER2"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[2]"
is_hex = true

[[tlm_field]]
name = "USER3"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[3]"
is_hex = true

[[tlm_field]]
name = "USER4"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[4]"
is_hex = true

[[tlm_field]]
name = "USER5"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[5]"
is_hex = true

[[tlm_field]]
name = "USER6"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[6]"
is_hex = true

[[tlm_field]]
name = "USER7"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[7]"
is_hex = true

[[tlm_field]]
name = "USER8"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[8]"
is_hex = true

[[tlm_field]]
name = "USER9"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[9]"
is_hex = true

[[tlm_field]]
name = "USER10"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[10]"
is_hex = true

[[tlm_field]]
name = "USER11"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[11]"
is_hex = true

[[tlm_field]]
name = "USER12"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[12]"
is_hex = true

[[tlm_field]]
name = "USER13"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[13]"
is_hex = true

[[tlm_field]]
name = "USER14"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[14]"
is_hex = true

[[tlm_field]]
name = "USER15"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[15]"
is_hex = true

[[tlm_field]]
name = "USER16"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[16]"
is_hex = true

[[tlm_field]]
name = "USER17"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[17]"
is_hex = true

[[tlm_field]]
name = "USER18"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[18]"
is_hex = true

[[tlm_field]]
name = "USER19"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[19]"
is_hex = true

[[tlm_field]]
name = "USER20"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[20]"
is_hex = true

[[tlm_field]]
name = "USER21"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[21]"
is_hex = true

[[tlm_field]]
name = "USER22"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[22]"
is_hex = true

[[tlm_field]]
name = "USER23"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[23]"
is_hex = true

[[tlm_field]]
name = "USER24"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[24]"
is_hex = true

[[tlm_field]]
name = "USER25"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[25]"
is_hex = true

[[tlm_field]]
name = "USER26"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[26]"
is_hex = true

[[tlm_field]]
name = "USER27"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[27]"
is_hex = true

[[tlm_field]]
name = "USER28"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[28]"
is_hex = true

[[tlm_field]]
name = "USER29"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[29]"
is_hex = true

[[tlm_field]]
name = "USER30"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[30]"
is_hex = true

[[tlm_field]]
name = "USER31"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[31]"
is_hex = true

[[tlm_field]]
name = "USER32"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[32]"
is_hex = true

[[tlm_field]]
name = "USER33"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[33]"
is_hex = true

[[tlm_field]]
name = "USER34"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[34]"
is_hex = true

[[tlm_field]]
name = "USER35"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[35]"
is_hex = true

[[tlm_field]]
name = "USER36"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[36]"
is_hex = true

[[tlm_field]]
name = "USER37"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[37]"
is_hex = true

[[tlm_field]]
name = "USER38"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[38]"
is_hex = true

[[tlm_field]]
name = "USER39"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[39]"
is_hex = true

[[tlm_field]]
name = "USER40"
type = "uint8_t"
exp = "(uint8_t)GIT_REV_USER[40]"
is_hex = true

