obc = "MOBC"
Target = "OBC"
PacketID = "0x19"
"Enable/Disable" = "ENABLE"
IsRestricted = "FALSE"
"Local Var" = ""

[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.VER"
bitlen = 3
[[tlm_field.comp]]
name = "PH.TYPE"
bitlen = 1
[[tlm_field.comp]]
name = "PH.SH_FLAG"
bitlen = 1
[[tlm_field.comp]]
name = "PH.APID"
bitlen = 11


[[tlm_field]]
type = "uint16_t"
[[tlm_field.comp]]
name = "PH.SEQ_FLAG"
bitlen = 2
[[tlm_field.comp]]
name = "PH.SEQ_COUNT"
bitlen = 14


[[tlm_field]]
name = "PH.PACKET_LEN"
type = "uint16_t"

[[tlm_field]]
name = "SH.VER"
type = "uint8_t"

[[tlm_field]]
name = "SH.TI"
type = "uint32_t"

[[tlm_field]]
name = "SH.TLM_ID"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.GLOBAL_TIME"
type = "double"

[[tlm_field]]
name = "SH.ON_BOARD_SUBNET_TIME"
type = "uint32_t"

[[tlm_field]]
name = "SH.DEST_FLAGS"
type = "uint8_t"
is_hex = true

[[tlm_field]]
name = "SH.DR_PARTITION"
type = "uint8_t"

[[tlm_field]]
name = "MASTER_BC_ID"
type = "uint16_t"
exp = "telemetry_manager->master_bc_id"

[[tlm_field]]
name = "BC_INFO0.BC_ID"
type = "uint16_t"
exp = "telemetry_manager->bc_info[0].bc_id"

[[tlm_field]]
name = "BC_INFO0.BC_TYPE"
type = "uint8_t"
exp = "(uint8_t)telemetry_manager->bc_info[0].bc_type"
status = "6.2"

[[tlm_field]]
name = "BC_INFO1.BC_ID"
type = "uint16_t"
exp = "telemetry_manager->bc_info[1].bc_id"

[[tlm_field]]
name = "BC_INFO1.BC_TYPE"
type = "uint8_t"
exp = "(uint8_t)telemetry_manager->bc_info[1].bc_type"
status = "6.2"

[[tlm_field]]
name = "BC_INFO2.BC_ID"
type = "uint16_t"
exp = "telemetry_manager->bc_info[2].bc_id"

[[tlm_field]]
name = "BC_INFO2.BC_TYPE"
type = "uint8_t"
exp = "(uint8_t)telemetry_manager->bc_info[2].bc_type"
status = "6.2"

[[tlm_field]]
name = "BC_INFO3.BC_ID"
type = "uint16_t"
exp = "telemetry_manager->bc_info[3].bc_id"

[[tlm_field]]
name = "BC_INFO3.BC_TYPE"
type = "uint8_t"
exp = "(uint8_t)telemetry_manager->bc_info[3].bc_type"
status = "6.2"

[[tlm_field]]
name = "BC_INFO4.BC_ID"
type = "uint16_t"
exp = "telemetry_manager->bc_info[4].bc_id"

[[tlm_field]]
name = "BC_INFO4.BC_TYPE"
type = "uint8_t"
exp = "(uint8_t)telemetry_manager->bc_info[4].bc_type"
status = "6.2"

[[tlm_field]]
name = "BC_INFO5.BC_ID"
type = "uint16_t"
exp = "telemetry_manager->bc_info[5].bc_id"

[[tlm_field]]
name = "BC_INFO5.BC_TYPE"
type = "uint8_t"
exp = "(uint8_t)telemetry_manager->bc_info[5].bc_type"
status = "6.2"

[[tlm_field]]
name = "BC_INFO6.BC_ID"
type = "uint16_t"
exp = "telemetry_manager->bc_info[6].bc_id"

[[tlm_field]]
name = "BC_INFO6.BC_TYPE"
type = "uint8_t"
exp = "(uint8_t)telemetry_manager->bc_info[6].bc_type"
status = "6.2"

[[tlm_field]]
name = "BC_INFO7.BC_ID"
type = "uint16_t"
exp = "telemetry_manager->bc_info[7].bc_id"

[[tlm_field]]
name = "BC_INFO7.BC_TYPE"
type = "uint8_t"
exp = "(uint8_t)telemetry_manager->bc_info[7].bc_type"
status = "6.2"

[[tlm_field]]
name = "BC_INFO8.BC_ID"
type = "uint16_t"
exp = "telemetry_manager->bc_info[8].bc_id"

[[tlm_field]]
name = "BC_INFO8.BC_TYPE"
type = "uint8_t"
exp = "(uint8_t)telemetry_manager->bc_info[8].bc_type"
status = "6.2"

[[tlm_field]]
name = "BC_INFO9.BC_ID"
type = "uint16_t"
exp = "telemetry_manager->bc_info[9].bc_id"

[[tlm_field]]
name = "BC_INFO9.BC_TYPE"
type = "uint8_t"
exp = "(uint8_t)telemetry_manager->bc_info[9].bc_type"
status = "6.2"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX0"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx[0]"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX1"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx[1]"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX2"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx[2]"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX3"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx[3]"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX4"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx[4]"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX5"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx[5]"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX6"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx[6]"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX7"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx[7]"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX8"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx[8]"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX9"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx[9]"

[[tlm_field]]
name = "REG_INFO.MASTER.BC_INFO_IDX_USED_NUM"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.bc_info_idx_used_num"

[[tlm_field]]
name = "REG_INFO.MASTER.REG_PNTR_TO_IDX_OF_BC_INFO_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.tlm_register_pointer_to_idx_of_bc_info_idx"

[[tlm_field]]
name = "REG_INFO.MASTER.REG_PNTR_TO_BC_CMD_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.master.tlm_register_pointer_to_bc_cmd_idx"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX0"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx[0]"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX1"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx[1]"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX2"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx[2]"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX3"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx[3]"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX4"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx[4]"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX5"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx[5]"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX6"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx[6]"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX7"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx[7]"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX8"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx[8]"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX9"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx[9]"

[[tlm_field]]
name = "REG_INFO.HK_TLM.BC_INFO_IDX_USED_NUM"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.bc_info_idx_used_num"

[[tlm_field]]
name = "REG_INFO.HK_TLM.REG_PNTR_TO_IDX_OF_BC_INFO_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.tlm_register_pointer_to_idx_of_bc_info_idx"

[[tlm_field]]
name = "REG_INFO.HK_TLM.REG_PNTR_TO_BC_CMD_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.hk_tlm.tlm_register_pointer_to_bc_cmd_idx"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX0"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx[0]"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX1"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx[1]"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX2"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx[2]"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX3"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx[3]"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX4"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx[4]"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX5"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx[5]"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX6"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx[6]"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX7"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx[7]"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX8"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx[8]"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX9"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx[9]"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.BC_INFO_IDX_USED_NUM"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.bc_info_idx_used_num"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.REG_PNTR_TO_IDX_OF_BC_INFO_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.tlm_register_pointer_to_idx_of_bc_info_idx"

[[tlm_field]]
name = "REG_INFO.SYSTEM_TLM.REG_PNTR_TO_BC_CMD_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.system_tlm.tlm_register_pointer_to_bc_cmd_idx"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX0"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx[0]"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX1"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx[1]"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX2"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx[2]"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX3"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx[3]"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX4"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx[4]"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX5"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx[5]"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX6"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx[6]"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX7"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx[7]"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX8"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx[8]"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX9"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx[9]"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.BC_INFO_IDX_USED_NUM"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.bc_info_idx_used_num"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.REG_PNTR_TO_IDX_OF_BC_INFO_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.tlm_register_pointer_to_idx_of_bc_info_idx"

[[tlm_field]]
name = "REG_INFO.HIGH_FREQ_TLM.REG_PNTR_TO_BC_CMD_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.high_freq_tlm.tlm_register_pointer_to_bc_cmd_idx"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX0"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx[0]"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX1"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx[1]"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX2"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx[2]"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX3"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx[3]"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX4"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx[4]"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX5"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx[5]"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX6"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx[6]"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX7"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx[7]"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX8"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx[8]"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX9"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx[9]"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.BC_INFO_IDX_USED_NUM"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.bc_info_idx_used_num"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.REG_PNTR_TO_IDX_OF_BC_INFO_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.tlm_register_pointer_to_idx_of_bc_info_idx"

[[tlm_field]]
name = "REG_INFO.LOW_FREQ_TLM.REG_PNTR_TO_BC_CMD_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.low_freq_tlm.tlm_register_pointer_to_bc_cmd_idx"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX0"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx[0]"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX1"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx[1]"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX2"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx[2]"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX3"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx[3]"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX4"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx[4]"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX5"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx[5]"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX6"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx[6]"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX7"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx[7]"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX8"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx[8]"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX9"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx[9]"

[[tlm_field]]
name = "REG_INFO.RESERVE.BC_INFO_IDX_USED_NUM"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.bc_info_idx_used_num"

[[tlm_field]]
name = "REG_INFO.RESERVE.REG_PNTR_TO_IDX_OF_BC_INFO_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.tlm_register_pointer_to_idx_of_bc_info_idx"

[[tlm_field]]
name = "REG_INFO.RESERVE.REG_PNTR_TO_BC_CMD_IDX"
type = "uint8_t"
exp = "telemetry_manager->register_info.reserve.tlm_register_pointer_to_bc_cmd_idx"

[[tlm_field]]
name = "IS_INITED"
type = "uint8_t"
exp = "telemetry_manager->is_inited"

